"telegram_token": "1002130423:AAG1fk3_C4PSn3172SATn29jgtp5T7R5o60"
"telegram_api_url": "https://api.telegram.org/bot"
"recycling_api_url": "https://virtserver.swaggerhub.com/Trepka/mock/1.0.0/"
"geobase_api_url": "https://virtserver.swaggerhub.com/Trepka/Geobase2/1.0.0/"